### ISSUE TITLE
MAB question

### ISSUE THREAD

**Issue by PASSENGER128** [icandle/MAN#8]
Hello, I have a few questions I want to ask: 1. What does the RCAN-style block in your paper look like? 2. Why is it necessary to pass the Layer norm in the MAB block, and what is its main function? And Why layer norm?

**Comment by icandle** [comment]
1. RCAN block is organized as **Conv-Act-Conv-CA** as the depicted figure, thus for the RCAN-style MAB, we only replace the CA (Channel-Attention) with our MLKA:
![image](https://user-images.githubusercontent.com/39293311/206896977-2752968a-2102-48b3-adad-9707622d03d8.png)

2.  We employ layer normalization (LN) to stabilize the gradient of loss (**because of large multiply operations**) without the influence of batch dimension.

Why LN (or IN) rather than BN is two-fold:
      * Batch normalization hearts SR performance. Previous literature (like EDSR) suggests that BN removes essential instance details and brings annoying artifacts.
      * Batch normalization fails to prevent the crash. As illustrated following picture, the MAN with BN meets exploding gradient problem where the loss comes to **NaN**.

![image](https://user-images.githubusercontent.com/39293311/206897254-469dcce3-32c4-4a7a-a27e-9f8fa0466a9a.png)

Why LN than IN: We choose LN than IN for LN brings better performance (0.0x dB improvement) and more common In both CNN and Transformer in recent research.
